### PR TITLE
Add Text Mode system role to SLERT (bsc#1117734)

### PR DESCRIPTION
**Pull request by JeffreyCheung**

### CODE REVIEW

**Comment by JeffreyCheung** [comment]
Please help to review the changes.

**Review by jreidinger — APPROVED** [review]
LGTM

**Comment by JeffreyCheung** [comment]
Hi, do I need to do any thing here ?

**Comment by jreidinger** [comment]
@JeffreyCheung no, it is approved, so feel free to merge it.

**Pull request merged**
